runtime: python27
api_version: 1
threadsafe: true
service: default
handlers:
   - url: /
     static_files: dist/findfood/index.html
     upload: dist/findfood/index.html
     secure: always
   - url: /
     static_dir: dist/findfood
     secure: always
  